[package]
name = "mint-sniper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Interact with EVM compatible blockchains
ethers = { git = "https://github.com/gakonst/ethers-rs", features = ["ws", "rustls", "abigen"] }

# Loading .env variables
dotenv = "0.15.0"

# Running asynchronous threads
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

# For quick and easy discord alerts
reqwest = "0.11.0"
clap = { version = "4.1.6", features = ["derive", "cargo"] }
ethabi = "18.0.0"
colored = "2.0.0"
chrono = "0.4.23"